import os
import requests
import time
import sys

os_name = os.name
install_ollama = None
installer_config = {}
version = "0.1.1"

def ollama_getValue():
    global install_ollama
    install_ollama = input("Do you want to install Ollama? [Yes]/No ").strip().lower()
    if install_ollama in ["yes", ""]:
        install_ollama = True
    elif install_ollama == "no":
        print("Ollama is required to run, make sure it is installed before running Komli.")
        install_ollama = False
    else:
        print("Unknown Input, try again")
        ollama_getValue()

def askconfig():
    global installer_config
    print("Config")
    installer_config['webdir'] = input("Enter the web directory you want to host from? Default is [/] ").strip() or '/'
    installer_config['ai_name'] = input("Enter the name for your assistant? Default is [Komli] ").strip() or 'Komli'
    installer_config['model'] = input("Enter the name of the model you want to use? Default is [qwen2.5-coder:0.5b] ").strip() or 'qwen2.5-coder:0.5b'
    installer_config['sys_prompt'] = input("Enter the system prompt? Default is [You are a friendly assistant] ").strip() or 'You are a friendly assistant'
    installer_config['markdown'] = input("Enable Markdown? Default is [Yes]/No ").strip() or 'yes'
    installer_config['port'] = input("Enter the port to run on? Default is [5000] ").strip() or '5000'
    installer_config['max_tokens'] = input("Set max tokens per request? Default is [30000] ").strip() or '30000'
    
    if input("Download Python Modules? [Yes]/No ").strip().lower() in ["yes", ""]:
        error_count = 0
        modules = ["requests", "ollama", "flask", "markupsafe", "markdown", "bcrypt"]
        
        for module in modules:
            try:
                result = os.system(f'"{sys.executable}" -m pip install {module}')
                if result != 0:
                    print(f"Failed to install {module}")
                    error_count += 1
                else:
                    print(f"Successfully installed {module}")
            except Exception as e:
                print(f"Failed to install {module}: {e}")
                error_count += 1
        
        if error_count == len(modules):
            install_status = "failed"
        elif error_count >= 1:
            install_status = "partial"
        else:
            install_status = "success"
        
        print(f"{error_count} errors occurred, installation {install_status}!")

    ollama_getValue()
    if input("Save Config? [Yes]/No ").strip().lower() in ["yes", ""]:
        setConfig()

def setConfig():
    global installer_config
    # Determine the config file path (go up one directory from installer/)
    config_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config.cfg')
    
    # Write the proper config file format
    with open(config_file, 'w') as f:
        f.write(f"""# Generated by Komli Installer
[DEFAULT]
name = "{installer_config.get("ai_name", "Komli")}" 
sys_prompt = "{installer_config.get("sys_prompt", "You are a friendly assistant")}" 
model = "{installer_config.get("model", "qwen2.5-coder:0.5b")}" 
timezone = "UTC"
database_prefix = "komli_"
clean_console = "False"

[Web]
webdir = "{installer_config.get("webdir", "/")}" 
port = "{installer_config.get("port", "5000")}" 

[PROCESSING]
markdown = {str(installer_config.get("markdown", "yes").lower() == "yes").title()}

[TOKEN_LIMIT]
enable = False
max_tokens = {installer_config.get("max_tokens", "30000")}

[SYSTEM]
ver = "{version}"
debug = "False"
""")
    
    print(f'Configuration saved to {config_file}')

def main():
    """Main installer function"""
    try:
        if os_name == "nt":
            os.system("cls")
            print("Welcome to the Windows Komli Installer!")
            print(f"Komli Version: {version}")
            print("=" * 40)
            askconfig()
            if install_ollama:
                print("Downloading Ollama...")
                file_path = "OllamaSetup.exe"
                try:
                    response = requests.get("https://ollama.com/download/OllamaSetup.exe", stream=True)
                    if response.status_code == 200:
                        with open(file_path, 'wb') as file:
                            for chunk in response.iter_content(chunk_size=8192):
                                file.write(chunk)
                        print('File downloaded successfully')
                        time.sleep(0.5)
                        print("Installing Ollama...")
                        os.system(f'start /wait "" "{file_path}"')
                        print("Ollama installation completed!")
                        # Clean up the installer file
                        try:
                            os.remove(file_path)
                        except:
                            pass
                    else:
                        print(f'Failed to download file. Status code: {response.status_code}')
                        print('Please download Ollama manually from https://ollama.com')
                except Exception as e:
                    print(f'Error downloading Ollama: {e}')
                    print('Please download Ollama manually from https://ollama.com')
        else:
            os.system("clear")
            print("Welcome to the Unix/Linux/Mac Komli Installer!")
            print(f"Komli Version: {version}")
            print("=" * 40)
            askconfig()
            if install_ollama:
                print("Installing Ollama...")
                try:
                    result = os.system("curl -fsSL https://ollama.com/install.sh | sh")
                    if result == 0:
                        print("Ollama installation completed!")
                    else:
                        print("Ollama installation may have failed. Please check manually.")
                except Exception as e:
                    print(f"Error installing Ollama: {e}")
                    print("Please install Ollama manually from https://ollama.com")

        print("\nInstallation completed!")
        auto_run = input("Do you want to run komli now? [Yes]/No ").strip().lower()
        if auto_run in ["yes", ""]:
            print("Starting Komli...")
            os.system(f'"{sys.executable}" app.py')
        else:
            print("You can start Komli later by running 'python app.py'\nTip: If komli responds with 'Ai failed to respond' or similar, make sure you have pulled the model by running 'ollama pull qwen2.5-coder:0.5b' or the model you set in config.cfg")
        
    except KeyboardInterrupt:
        print("\n\nInstallation cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\nAn error occurred during installation: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
